version: 0.0
os: linux
files:
  - source: /deploy/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/scripts/start_server.sh
      timeout: 300
      runas: root
