version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y apache2
      - sudo python -m pip install --upgrade pip
      - sudo pip install flake8 pytest  

  pre_build:
    commands:
      - echo "Ejecutando linter..."
      - flake8 .  

  build:
    commands:
      - echo "Ejecutando tests..."
      - pytest 
      
  post_build:
    commands:
      - echo "Preparando artefacto para CodeDeploy..."
      - mkdir -p deploy
      - cp index.html deploy/
      - cp appspec.yml deploy/
      - cp -r scripts/ deploy/  

artifacts:
  files:
    - deploy/**/*
