version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Usa la versión de Python que necesites
    commands:
      - apt-get update -y
      - apt-get install -y apache2
      - python -m pip install --upgrade pip
      - pip install flake8 pytest  # Instala linter y framework de tests

  pre_build:
    commands:
      - echo "Ejecutando linter..."
      - flake8 .  # Ejecuta flake8 en el directorio actual

  build:
    commands:
      - echo "Ejecutando tests..."
      - pytest  # Ejecuta los tests

  post_build:
    commands:
      - echo "Preparando artefacto para CodeDeploy..."
      - mkdir -p deploy
      - cp index.html deploy/
      - cp appspec.yml deploy/
      - cp -r scripts/ deploy/  # Incluye scripts necesarios para la instalación

artifacts:
  files:
    - deploy/**/*
